spring.application.name=Api-Gateway
server.port=8080
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.reactor.netty.http.client=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
