server.port=8084
spring.application.name=booking-service


spring.datasource.url=jdbc:mysql://localhost:3306/bookingdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Circuit Breaker
resilience4j.circuitbreaker.instances.theatreService.register-health-indicator=true
resilience4j.circuitbreaker.instances.theatreService.sliding-window-size=10
resilience4j.circuitbreaker.instances.theatreService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.theatreService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.theatreService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.theatreService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.theatreService.automatic-transition-from-open-to-half-open-enabled=true
